# Generated by Django 5.1.2 on 2024-11-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BMSystem", "0004_book_stock_alter_book_isbn_myuser_borrowrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="book",
            name="published_date",
        ),
        migrations.AddField(
            model_name="book",
            name="published_year",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(default="", max_length=300),
        ),
    ]
