# Generated by Django 5.1.2 on 2024-11-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BMSystem", "0005_remove_book_isbn_remove_book_published_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_year",
            field=models.IntegerField(),
        ),
    ]
