# Generated by Django 5.1.2 on 2024-11-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BMSystem", "0006_alter_book_published_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
