# Generated by Django 5.1.2 on 2024-11-14 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BMSystem", "0008_alter_book_published_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="published_year",
        ),
        migrations.AddField(
            model_name="book",
            name="published_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(max_length=100),
        ),
    ]
