# Generated by Django 5.1.2 on 2024-11-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "BMSystem",
            "0010_remove_myuser_groups_remove_myuser_user_permissions_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(default="", max_length=13, unique=True),
        ),
    ]
