# Generated by Django 5.1.2 on 2024-12-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BMSystem", "0013_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="borrow_count",
            field=models.IntegerField(default=0),
        ),
    ]
