# Generated by Django 5.1.2 on 2024-12-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BMSystem", "0015_profile_identity_card_profile_name_borrowrecord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowrecord",
            name="book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="borrow_records",
                to="BMSystem.book",
            ),
        ),
    ]
