# Generated by Django 5.1.2 on 2024-12-16 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BMSystem", "0016_alter_borrowrecord_book"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowrecord",
            name="due_date",
            field=models.DateField(default='2024-12-18'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="borrowrecord",
            name="book",
            field=models.ForeignKey(
                default='1',
                on_delete=django.db.models.deletion.CASCADE,
                to="BMSystem.book",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="borrowrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
